feat(update)!: prevent updating to an incompatible release
When the python rewrite gets merged into master, 1.7.1 will still try to
upgrade to the python rewrite, even though the locations of certain code
will not be there anymore. This adds a check to make sure Pacstall can't
upgrade to a pythonic version

diff --git a/pacstall b/pacstall
--- a/pacstall
+++ b/pacstall
@@ -486,7 +486,11 @@ while [[ ! "$1" == "--" ]]; do
 					USERNAME="pacstall"
 				fi
 			fi
-
+			if curl --output /dev/null --silent --head --fail https://raw.githubusercontent.com/"$USERNAME"/pacstall/"$BRANCH"/pyproject.toml; then
+				fancy_message error "The repository you are trying to upgrade to contains a version of pacstall that cannot be updated from $(pacstall -V)"
+				fancy_message error "Visit https://github.com/$USERNAME/pacstall/tree/$BRANCH for more information on how to update"
+				exit 1
+			fi
 			sudo wget -q -N https://raw.githubusercontent.com/"$USERNAME"/pacstall/"$BRANCH"/misc/scripts/update.sh -P "$STGDIR/scripts" 2> /dev/null
 			source "$STGDIR/scripts/update.sh"
 			exit 0
