chore(misc): pre-commit hooks

diff --git a/pacstall b/pacstall
--- a/pacstall
+++ b/pacstall
@@ -121,9 +121,9 @@ function fancy_message() {
 
 	case ${MESSAGE_TYPE} in
 		info) echo -e "[${BGreen}+${NC}] INFO: ${MESSAGE}" ;;
-		warn) >&2 echo -e "[${BYellow}*${NC}] WARNING: ${MESSAGE}" ;;
-		error) >&2 echo -e "[${BRed}!${NC}] ERROR: ${MESSAGE}" ;;
-		*) >&2 echo -e "[${BOLD}?${NORMAL}] UNKNOWN: ${MESSAGE}" ;;
+		warn) echo >&2 -e "[${BYellow}*${NC}] WARNING: ${MESSAGE}" ;;
+		error) echo >&2 -e "[${BRed}!${NC}] ERROR: ${MESSAGE}" ;;
+		*) echo >&2 -e "[${BOLD}?${NORMAL}] UNKNOWN: ${MESSAGE}" ;;
 	esac
 }
 
@@ -194,15 +194,15 @@ function ask() {
 	done
 }
 function check_url() {
-    if [[ "${1}" == "file://"* ]]; then
-    	if [[ -f "${1}" ]]; then
-    	  true
-    	fi
-    else
+	if [[ ${1} == "file://"* ]]; then
+		if [[ -f ${1} ]]; then
+			true
+		fi
+	else
 		http_code="$(curl -o /dev/null -s --head --write-out '%{http_code}\n' -- "${1}")"
 		case "${http_code}" in
 			000)
-				if [[ "${1}" == *"packagelist" ]]; then
+				if [[ ${1} == *"packagelist" ]]; then
 					fancy_message error "Packagelist not found"
 				else
 					fancy_message error "Failed to download file, check your connection"
