-Qd will fail if no package is specified
Former-commit-id: 70647a036b78ffd842812482a07432953fb855ac [formerly 3dc93efc1f033cfc26ac7867f3e296b328b9a255] [formerly 819dd40dfb4a38222af1d7229422a77900d70358]
Former-commit-id: 0f0e624d9e19eaa685d5d4fc5b09a15839e0f58b
Former-commit-id: 72ca3654873df62e3f656cee5f7f1ad85b9c034b

diff --git a/pacstall b/pacstall
--- a/pacstall
+++ b/pacstall
@@ -165,6 +165,10 @@ while test $# -gt 0; do
       PACKAGE=$2
       REPO=$(cat /usr/share/pacstall/repo/pacstallrepo.txt)
       URL="https://raw.githubusercontent.com/$REPO/master/packages/$PACKAGE/$PACKAGE.pacscript"
+      if [[ -z "$PACKAGE" ]]; then
+          fancy_message error "You failed to specify a package"
+          exit 1
+      fi
       if curl --output /dev/null --silent --head --fail "$URL"; then
           source <(curl -s $URL) >/dev/null 2>&1
       else
