Chan: Cleanup `pacstall`

diff --git a/pacstall b/pacstall
--- a/pacstall
+++ b/pacstall
@@ -22,79 +22,87 @@
 # You should have received a copy of the GNU General Public License
 # along with Pacstall. If not, see <https://www.gnu.org/licenses/>.
 
-BOLD=$(tput bold)
-NORMAL=$(tput sgr0)
-NC='\033[0m'
+# Configuration
+export LC_ALL=C
+export LOGDIR="/var/log/pacstall"
+export SRCDIR="/tmp/pacstall"
+export STGDIR="/usr/share/pacstall"
+export STOWDIR="/usr/src/pacstall"
+
+# Colors
+export BOLD=$(tput bold)
+export NORMAL=$(tput sgr0)
+export NC='\033[0m'
 # Curtesy of https://stackoverflow.com/a/28938235/13449010
 # Regular Colors
-BLACK='\033[0;30m'        # Black
-RED='\033[0;31m'          # Red
-GREEN='\033[0;32m'        # Green
-YELLOW='\033[0;33m'       # Yellow
-BLUE='\033[0;34m'         # Blue
-PURPLE='\033[0;35m'       # Purple
-CYAN='\033[0;36m'         # Cyan
-WHITE='\033[0;37m'        # White
+export BLACK='\033[0;30m'        # Black
+export RED='\033[0;31m'          # Red
+export GREEN='\033[0;32m'        # Green
+export YELLOW='\033[0;33m'       # Yellow
+export BLUE='\033[0;34m'         # Blue
+export PURPLE='\033[0;35m'       # Purple
+export CYAN='\033[0;36m'         # Cyan
+export WHITE='\033[0;37m'        # White
 
 # Bold
-BBlack='\033[1;30m'       # Black
-BRed='\033[1;31m'         # Red
-BGreen='\033[1;32m'       # Green
-BYellow='\033[1;33m'      # Yellow
-BBlue='\033[1;34m'        # Blue
-BPurple='\033[1;35m'      # Purple
-BCyan='\033[1;36m'        # Cyan
-BWhite='\033[1;37m'       # White
+export BBlack='\033[1;30m'       # Black
+export BRed='\033[1;31m'         # Red
+export BGreen='\033[1;32m'       # Green
+export BYellow='\033[1;33m'      # Yellow
+export BBlue='\033[1;34m'        # Blue
+export BPurple='\033[1;35m'      # Purple
+export BCyan='\033[1;36m'        # Cyan
+export BWhite='\033[1;37m'       # White
 
 # Underline
-UBlack='\033[4;30m'       # Black
-URed='\033[4;31m'         # Red
-UGreen='\033[4;32m'       # Green
-UYellow='\033[4;33m'      # Yellow
-UBlue='\033[4;34m'        # Blue
-UPurple='\033[4;35m'      # Purple
-UCyan='\033[4;36m'        # Cyan
-UWhite='\033[4;37m'       # White
+export UBlack='\033[4;30m'       # Black
+export URed='\033[4;31m'         # Red
+export UGreen='\033[4;32m'       # Green
+export UYellow='\033[4;33m'      # Yellow
+export UBlue='\033[4;34m'        # Blue
+export UPurple='\033[4;35m'      # Purple
+export UCyan='\033[4;36m'        # Cyan
+export UWhite='\033[4;37m'       # White
 
 # Background
-On_Black='\033[40m'       # Black
-On_Red='\033[41m'         # Red
-On_Green='\033[42m'       # Green
-On_Yellow='\033[43m'      # Yellow
-On_Blue='\033[44m'        # Blue
-On_Purple='\033[45m'      # Purple
-On_Cyan='\033[46m'        # Cyan
-On_White='\033[47m'       # White
+export On_Black='\033[40m'       # Black
+export On_Red='\033[41m'         # Red
+export On_Green='\033[42m'       # Green
+export On_Yellow='\033[43m'      # Yellow
+export On_Blue='\033[44m'        # Blue
+export On_Purple='\033[45m'      # Purple
+export On_Cyan='\033[46m'        # Cyan
+export On_White='\033[47m'       # White
 
 # High Intensity
-IBlack='\033[0;90m'       # Black
-IRed='\033[0;91m'         # Red
-IGreen='\033[0;92m'       # Green
-IYellow='\033[0;93m'      # Yellow
-IBlue='\033[0;94m'        # Blue
-IPurple='\033[0;95m'      # Purple
-ICyan='\033[0;96m'        # Cyan
-IWhite='\033[0;97m'       # White
+export IBlack='\033[0;90m'       # Black
+export IRed='\033[0;91m'         # Red
+export IGreen='\033[0;92m'       # Green
+export IYellow='\033[0;93m'      # Yellow
+export IBlue='\033[0;94m'        # Blue
+export IPurple='\033[0;95m'      # Purple
+export ICyan='\033[0;96m'        # Cyan
+export IWhite='\033[0;97m'       # White
 
 # Bold High Intensity
-BIBlack='\033[1;90m'      # Black
-BIRed='\033[1;91m'        # Red
-BIGreen='\033[1;92m'      # Green
-BIYellow='\033[1;93m'     # Yellow
-BIBlue='\033[1;94m'       # Blue
-BIPurple='\033[1;95m'     # Purple
-BICyan='\033[1;96m'       # Cyan
-BIWhite='\033[1;97m'      # White
+export BIBlack='\033[1;90m'      # Black
+export BIRed='\033[1;91m'        # Red
+export BIGreen='\033[1;92m'      # Green
+export BIYellow='\033[1;93m'     # Yellow
+export BIBlue='\033[1;94m'       # Blue
+export BIPurple='\033[1;95m'     # Purple
+export BICyan='\033[1;96m'       # Cyan
+export BIWhite='\033[1;97m'      # White
 
 # High Intensity backgrounds
-On_IBlack='\033[0;100m'   # Black
-On_IRed='\033[0;101m'     # Red
-On_IGreen='\033[0;102m'   # Green
-On_IYellow='\033[0;103m'  # Yellow
-On_IBlue='\033[0;104m'    # Blue
-On_IPurple='\033[0;105m'  # Purple
-On_ICyan='\033[0;106m'    # Cyan
-On_IWhite='\033[0;107m'   # White
+export On_IBlack='\033[0;100m'   # Black
+export On_IRed='\033[0;101m'     # Red
+export On_IGreen='\033[0;102m'   # Green
+export On_IYellow='\033[0;103m'  # Yellow
+export On_IBlue='\033[0;104m'    # Blue
+export On_IPurple='\033[0;105m'  # Purple
+export On_ICyan='\033[0;106m'    # Cyan
+export On_IWhite='\033[0;107m'   # White
 
 function ask() {
   local prompt default reply
@@ -107,7 +115,6 @@ function ask() {
     default='N'
   else
     prompt="${GREEN}y${NC}/${RED}n${NC}"
-    default=''
   fi
 
   while true; do
@@ -116,7 +123,7 @@ function ask() {
 
     # Read the answer (use /dev/tty in case stdin is redirected from somewhere else)
     if [[ -z "$DISABLE_PROMPTS" ]]; then
-      read -r reply </dev/tty
+      read -r reply < /dev/tty
     else
       echo "$default"
       reply=$default
@@ -143,11 +150,8 @@ function fancy_message() {
   local RED="\e[31m"
   local GREEN="\e[32m"
   local YELLOW="\e[33m"
-  local RESET="\e[0m"
-  local MESSAGE_TYPE=""
-  local MESSAGE=""
-  MESSAGE_TYPE="${1}"
-  MESSAGE="${2}"
+  local MESSAGE_TYPE="${1}"
+  local MESSAGE="${2}"
 
   case ${MESSAGE_TYPE} in
     info) echo -e "[${BGreen}+${NC}] INFO: ${MESSAGE}";;
@@ -180,22 +184,19 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
       -V --version, Prints pacstall version
       -L --list, Lists installed packages
       -Up --upgrade, Upgrades packages
-      -Qd --query-depends, Get dependencies of package
       -Qi --query-info, Get package info
        "
       exit 0
     ;;
 
     -I|--install)
-      export LC_ALL=C
-
       function trap_ctrlc () {
 	      fancy_message warn "the installation of $2 was interrupted, removing files"
-	      rm -rf /tmp/pacstall/*
+	      rm -rf "${SRCDIR:?}"/* # :? makes bash error out in case SRCDIR is empty, saving us from yonking /* directory by mistake
         exit 2
       }
-
       trap "trap_ctrlc" 2
+
       PACKAGE=$2
       if [[ -z "$PACKAGE" ]]; then
         fancy_message error "You failed to specify a package"
@@ -203,110 +204,106 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
       fi
 
       # Make the directory if not exist
-      if [[ ! -e /usr/share/pacstall/repo/ ]]; then
-        sudo mkdir -p /usr/share/pacstall/repo
-        sudo touch /usr/share/pacstall/repo/pacstallrepo.txt
+      if [[ ! -e "$STGDIR/repo/" ]]; then
+        sudo mkdir -p "$STGDIR/repo"
+        sudo touch "$STGDIR/repo/pacstallrepo.txt"
 	      sudo pacstall -C
       fi
 
       INSTALLING=1
-      REPO=$(cat /usr/share/pacstall/repo/pacstallrepo.txt)
+      HOMEDIR=$HOME
+      REPO=$(cat "$STGDIR/repo/pacstallrepo.txt")
+      URL="$REPO/packages/$PACKAGE/$PACKAGE.pacscript"
 
-      export HOMEDIR=$HOME
-      export REPO=$(cat /usr/share/pacstall/repo/pacstallrepo.txt)
-      export URL="$REPO/packages/$PACKAGE/$PACKAGE.pacscript"
-
-      source /usr/share/pacstall/scripts/download.sh
+      source "$STGDIR/scripts/download.sh"
       exit 0
     ;;
 
     -Il|--install-local)
-      REPO=$(cat /usr/share/pacstall/repo/pacstallrepo.txt) 
-      INPUT=$2
+      REPO=$(cat "$STGDIR/repo/pacstallrepo.txt") 
+      INPUT="$(echo "$2" | sed 's/\..*$//')" # Removes the .pacscript suffix
 
-      # If string is absolute dir
-      if [[ "$string" == */* ]] || [[ "$string" == *\\* ]] ; then
-        cd $(pwd)
-        parentdir="$(dirname "$INPUT")"
-        eval dir="$parentdir"
-        cd "$dir"
-        PACKAGE=$(basename "$dir")
-        PACKAGE="$(echo "$PACKAGE" | sed 's/\..*$//')"
-
-      else
-        # If it's in pwd
-        PACKAGE=$(echo "$INPUT" | sed 's/:.*//')
+      # Check if the file exist (both .pacscript and without)
+      if [[ ! -f "$2" && ! -f "$INPUT" ]]; then
+        fancy_message error "$2 does not exist"
+        exit 1
       fi
 
-      source /usr/share/pacstall/scripts/install-local.sh
+      cd "$(dirname "$INPUT")" || (fancy_message error "The directory does not exist"; exit 1)
+      PACKAGE="$(basename "$INPUT")"
+
+      source "$STGDIR/scripts/install-local.sh"
       exit 0
     ;;
 
     -S|--search)
-      source /usr/share/pacstall/scripts/search.sh
+      source "$STGDIR/scripts/search.sh"
     ;;
 
     -R|--remove)
       PACKAGE=$2
-      
-      # Check if $2 is filled (not empty) because if not, stow will remove every package (from experience, oof)
+      cd "$STOWDIR" || (fancy_message error "Package directory seems to be missing"; exit 1)
+
+      # Run preliminary checks
       if [[ -z "$PACKAGE" ]]; then
         fancy_message error "You failed to specify a package"
         exit 1
       fi
 
-      source /var/log/pacstall_installed/"$PACKAGE" >/dev/null 2>&1
-
-      if [ -d "/usr/src/pacstall/$PACKAGE" ]; then
-        fancy_message info "Removing symlinks"
-        cd /usr/src/pacstall
-        sudo stow -D "$PACKAGE"
-
-        fancy_message info "Removing package"
-        source /var/log/pacstall_installed/"$PACKAGE"
-        sudo rm -rf /usr/src/pacstall/"$PACKAGE"
-        hash -r
-
-	      if [[ $_removescript == "yes" ]] ; then
-	        fancy_message info "Running post removal script"
-	        REPO=$(cat /usr/share/pacstall/repo/pacstallrepo.txt)
-          # Sources the output of /var/cache/pacstall/pkg/version/pkg.pacscript so we don't have to download scripts from the repo
-          source <(cat /var/cache/pacstall/"$PACKAGE"/$(pacstall -V "$PACKAGE")/"$PACKAGE".pacscript)
-	        removescript
-        fi
-
-        if [ -n "$dependencies" ]; then
-          fancy_message info "You may want to remove ${BLUE}$dependencies${NC}"
-        fi
-
-        sudo rm -f /var/log/pacstall_installed/"$PACKAGE"
-        exit 0
-
-      else
+      if [[ ! -d "$PACKAGE" ]]; then
         fancy_message error "$PACKAGE is not installed or not properly symlinked"
         exit 1
       fi
+
+      # Removal starts from here
+      source "$LOGDIR/installed/$PACKAGE" > /dev/null 2>&1
+
+      fancy_message info "Removing symlinks"
+      sudo stow -D "$PACKAGE"
+
+      fancy_message info "Removing package"
+      sudo rm -rf "$PACKAGE"
+      hash -r
+
+	    if [[ $_removescript == "yes" ]] ; then
+	      fancy_message info "Running post removal script"
+	      REPO=$(cat "$STGDIR/repo/pacstallrepo.txt")
+        # Sources the output of /var/cache/pacstall/pkg/version/pkg.pacscript so we don't have to download scripts from the repo
+        source <(cat "/var/cache/pacstall/$PACKAGE/$(pacstall -V "$PACKAGE")/$PACKAGE.pacscript")
+	      removescript
+      fi
+
+      if [ -n "$_dependencies" ]; then
+        fancy_message info "You may want to remove ${BLUE}$_dependencies${NC}"
+      fi
+
+      sudo rm -f "$LOGDIR/installed/$PACKAGE"
+      exit 0
     ;;
 
     -C|--change-repo)
-      if [[ -z "$2" ]]; then
-      . /usr/share/pacstall/scripts/change-repo.sh
+      REPO="$2"
+
+      if [[ -z "$REPO" ]]; then
+        source "$STGDIR/scripts/change-repo.sh"
       else
-        echo "$2" | sudo tee /usr/share/pacstall/repo/pacstallrepo.txt >/dev/null 2>&1
+        echo "$REPO" | sudo tee "$STGDIR/repo/pacstallrepo.txt" > /dev/null 2>&1
         exit 0
       fi
     ;;
 
     -V|--version)
-      if [[ -z "$2" ]]; then
+      PACKAGE="$2"
+
+      if [[ -z "$PACKAGE" ]]; then
         echo -e "1.4 ${BICyan}Turkuaz${NC}"
         exit 0
 
       else
-        if pacstall -Qi "$2" | grep 'version' | cut -d ":" -f2 | sed 's/ //g'; then
+        if pacstall -Qi "$PACKAGE" | grep 'version' | cut -d ":" -f2 | sed 's/ //g'; then
           exit 0
         else
-          fancy_message error "$2 doesn't exist"
+          fancy_message error "$PACKAGE doesn't exist"
           exit 1
         fi
       fi
@@ -317,16 +314,16 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
       BRANCH="$3"
 
       if [[ -z "$BRANCH" ]]; then
-        if test -f "/usr/share/pacstall/repo/update"; then
-           BRANCH=$(sed 's/.*\ //' /usr/share/pacstall/repo/update)
+        if [[ -f "$STGDIR/repo/update" ]]; then
+           BRANCH=$(sed 's/.*\ //' "$STGDIR/repo/update")
         else 
           BRANCH="master"
         fi
       fi
 
       if [[ -z "$USERNAME" ]]; then
-        if test -f "/usr/share/pacstall/repo/update"; then
-           USERNAME=$(sed 's/\s.*$//' /usr/share/pacstall/repo/update)
+        if [[ -f "$STGDIR/repo/update" ]]; then
+           USERNAME=$(sed 's/\s.*$//' "$STGDIR/repo/update")
         else
            USERNAME="pacstall"
         fi
@@ -334,15 +331,15 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
 
       if ask "Are you sure you want to update pacstall?" Y; then
         for i in {change-repo.sh,search.sh,download.sh,install-local.sh,upgrade.sh}; do
-          sudo wget -q -N https://raw.githubusercontent.com/"$USERNAME"/pacstall/"$BRANCH"/misc/scripts/"$i" -P /usr/share/pacstall/scripts 2>/dev/null 
+          sudo wget -q -N https://raw.githubusercontent.com/"$USERNAME"/pacstall/"$BRANCH"/misc/scripts/"$i" -P "$STGDIR/scripts" 2> /dev/null 
         done
 
-        sudo wget -q -N https://raw.githubusercontent.com/"$USERNAME"/pacstall/"$BRANCH"/pacstall -P /bin 2>/dev/null
+        sudo wget -q -N https://raw.githubusercontent.com/"$USERNAME"/pacstall/"$BRANCH"/pacstall -P /bin 2> /dev/null
         sudo mkdir -p /usr/share/bash-completion/completions
-        sudo wget -q -O /usr/share/bash-completion/completions/pacstall https://raw.githubusercontent.com/"$USERNAME"/pacstall/"$BRANCH"/misc/completion/bash 2>/dev/null
+        sudo wget -q -O /usr/share/bash-completion/completions/pacstall https://raw.githubusercontent.com/"$USERNAME"/pacstall/"$BRANCH"/misc/completion/bash 2> /dev/null
 
-        if command -v fish &>/dev/null; then
-          sudo wget -q -O /usr/share/fish/vendor_completions.d/pacstall.fish https://raw.githubusercontent.com/"$USERNAME"/pacstall/"$BRANCH"/misc/completion/fish 2>/dev/null
+        if command -v fish &> /dev/null; then
+          sudo wget -q -O /usr/share/fish/vendor_completions.d/pacstall.fish https://raw.githubusercontent.com/"$USERNAME"/pacstall/"$BRANCH"/misc/completion/fish 2> /dev/null
         fi
 
         echo '
@@ -355,7 +352,7 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
         fancy_message info "You are at version $(pacstall -V)"
         fancy_message warn "Be sure to check our GitHub release page to make sure you have no incompatible code: https://github.com/$USERNAME/pacstall/tree/$BRANCH"
 
-        echo "$USERNAME $BRANCH" | sudo tee /usr/share/pacstall/repo/update >/dev/null
+        echo "$USERNAME $BRANCH" | sudo tee "$STGDIR/repo/update" > /dev/null
         exit 0
       else
         exit 1
@@ -363,14 +360,11 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
     ;;
 
     -L|--list)
-      export LC_ALL=C
-
-      /bin/ls -1aA /usr/src/pacstall
+      /bin/ls -1aA "$STOWDIR"
       exit 0
     ;;
 
     -D|--download)
-      export LC_ALL=C
       PACKAGE=$2
 
       if [[ -z "$PACKAGE" ]]; then
@@ -379,42 +373,17 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
       fi
 
       INSTALLING=0
-      REPO=$(cat /usr/share/pacstall/repo/pacstallrepo.txt)
-      source /usr/share/pacstall/scripts/download.sh
-      exit 0
-    ;;
-
-    -Qd|--query-depends)
-      export LC_ALL=C
-      PACKAGE=$2
-      REPO=$(cat /usr/share/pacstall/repo/pacstallrepo.txt)
-      URL="$REPO/packages/$PACKAGE/$PACKAGE.pacscript"
-
-      if [[ -z "$PACKAGE" ]]; then
-        fancy_message error "You failed to specify a package"
-        exit 1
-      fi
-
-      if curl --output /dev/null --silent --head --fail "$URL"; then
-        source <(curl -s "$URL") >/dev/null 2>&1
-      else
-        fancy_message error "$PACKAGE doesn't seem to exist"
-        exit 1
-      fi
-
-      echo -e "${GREEN}${BOLD}build_depends${NORMAL}${NC}: \"$build_depends\""
-      echo -e "${GREEN}${BOLD}depends${NORMAL}${NC}: \"$depends\""
+      REPO=$(cat "$STGDIR/repo/pacstallrepo.txt")
+      source "$STGDIR/scripts/download.sh"
       exit 0
     ;;
 
     -Up|--upgrade)
-      export LC_ALL=C
-      . /usr/share/pacstall/scripts/upgrade.sh
+      source "$STGDIR/scripts/upgrade.sh"
       exit 0
     ;;
 
     -Qi|--query-info)
-      export LC_ALL=C
       PACKAGE=$2
 
       if [[ -z "$PACKAGE" ]]; then
@@ -422,15 +391,15 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
         exit 1
       fi
 
-      if [ ! -f /var/log/pacstall_installed/"$PACKAGE" ]; then
+      if [ ! -f "$LOGDIR/installed/$PACKAGE" ]; then
         fancy_message error "Package does not exist"
         exit 1
       fi
 
-      source /var/log/pacstall_installed/"$PACKAGE"
+      source "$LOGDIR/installed/$PACKAGE"
       echo "name: $PACKAGE"
       echo "version: $_version"
-      echo "size: $(du -sh /usr/src/pacstall/"$PACKAGE" 2>/dev/null | awk '{print $1}')"
+      echo "size: $(du -sh "$STOWDIR"/"$PACKAGE" 2> /dev/null | awk '{print $1}')"
       echo "description: ""$_description"""
       echo "date installed: ""$_date"""
 
@@ -455,15 +424,14 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
     ;;
 
     -T|--tree)
-      LC_ALL=C
       PACKAGE="$2"
 
-      if [ -d "/usr/src/pacstall/$PACKAGE" ]; then
-        tree -C /usr/src/pacstall/"$PACKAGE" | sed "s/\/usr\/src\/pacstall\/$PACKAGE/\//g"
-      else
-        fancy_message error "Package does not exist"
+      if [[ ! -d "$STOWDIR/$PACKAGE" ]]; then
+        fancy_message error "$PACKAGE does not exist"
         exit 1
       fi
+
+      tree -C "$STOWDIR/$PACKAGE" | sed "s/\/usr\/src\/pacstall\/$PACKAGE/\//g"
     ;;
 
     *)
