Update pacstall
Former-commit-id: 8f8db5284dc85542181f3cabab2f967b7ac502d4
Former-commit-id: b856e0656e2cccefb7b02e448a8fb5c7c165a9fa

diff --git a/pacstall b/pacstall
--- a/pacstall
+++ b/pacstall
@@ -59,8 +59,11 @@ while test $# -gt 0; do
       echo "Indexing..."
       echo $package >> /etc/pacstall_packages
       sudo sed -i '$!N; /^\(.*\)\n\1$/!P; D' /etc/pacstall_packages
+      if [ "$?" != "0" ]; then
+          echo "[Error] install failed!" 1>&2
+      exit 1
+      fi
       echo -e "${CYAN}Done!!${NC}"
-      exit 0
       ;;
     -S)
      search=$2
