Updated pacstall
Former-commit-id: 110e22c409b1f0e4691b4fd9a839d7a5ed255640
Former-commit-id: b61556a49fcff5b18e185df1f77efde43026c368

diff --git a/pacstall b/pacstall
--- a/pacstall
+++ b/pacstall
@@ -145,7 +145,12 @@ while test $# -gt 0; do
         echo -e "1.0.4 ${COLOR}Celeste${NC}"
         exit 0
       else
-        echo $(pacstall -L | grep '$2' | cut -d' ' -f2-)
+        if [[ $(echo $(pacstall -L | grep '$2' | cut -d' ' -f2-)) ]]; then
+          exit
+        else
+          fancy_message error "Invalid input"
+          exit 1
+        fi
       fi
       ;;
     -U|--update)
