feat(main): add `PACSTALL_XTRACE{FD,LOG}` for debugging (#1461)
Co-authored-by: oklopfer <104327997+oklopfer@users.noreply.github.com>

diff --git a/pacstall b/pacstall
--- a/pacstall
+++ b/pacstall
@@ -46,11 +46,30 @@ export PACSTALL_INSTALL=1
 
 PACSTALL_DEBUG=0
 if [[ "${1}" == "-x" || "${1}" == "--debug" ]]; then
-  set -x
-  PACSTALL_DEBUG=1
-  shift 1
+    if [[ -n ${PACSTALL_XTRACELOG} && -n ${PACSTALL_XTRACEFD} ]]; then
+        if ! [[ ${PACSTALL_XTRACEFD} =~ ^[0-9]+$ ]]; then
+            {
+                # avoid having to duplicate gettext string used in later checks
+                printf '[\033[1;31m!\033[0m] \033[1mERROR\033[0m: ';
+                printf $"'%s' must be an unsigned integer" 'PACSTALL_XTRACEFD';
+                # avoid having the newline in a gettext string
+                printf '\n';
+            } >&2
+            exit 1
+        fi
+        # Separate elevated log file because of permissions issues
+        if [[ $PACSTALL_ELEVATED ]]; then
+            eval "exec ${PACSTALL_XTRACEFD}>'${PACSTALL_XTRACELOG}.elevated'"
+        else
+            eval "exec ${PACSTALL_XTRACEFD}>'${PACSTALL_XTRACELOG}'"
+        fi
+        export BASH_XTRACEFD="${PACSTALL_XTRACEFD}"
+    fi
+    set -x
+    PACSTALL_DEBUG=1
+    shift 1
 else
-  set +x
+    set +x
 fi
 export PACSTALL_DEBUG
 
@@ -810,8 +829,15 @@ function elevate() {
             PACSTALL_DOWNLOADER="$PACSTALL_DOWNLOADER" PACSTALL_PAYLOAD="$PACSTALL_PAYLOAD" \
             PACSTALL_TMPDIR="$PACSTALL_TMPDIR" NO_COLOR="$NO_COLOR" SUDO_USER="${SUDO_USER}" \
             DISABLE_PROMPTS="$DISABLE_PROMPTS" PACSTALL_ELEVATED=true \
+            PACSTALL_XTRACELOG="${PACSTALL_XTRACELOG}" PACSTALL_XTRACEFD="${PACSTALL_XTRACEFD}" \
             pacstall $debug $keep $build $nocheck $quiet $nosandbox $@
-        exit $?
+        exit_code=$?
+        if [[ -n ${debug} && -n ${PACSTALL_XTRACELOG} && -n ${PACSTALL_XTRACEFD} ]]; then
+            set +x
+            tail -n +1 -v "${PACSTALL_XTRACELOG}.elevated" >> "${PACSTALL_XTRACELOG}" \
+                && sudo rm -rf "${PACSTALL_XTRACELOG}.elevated"
+        fi
+        exit ${exit_code}
     fi
 }
 
