rm!(install-local): merge `-Il` with `-I`

diff --git a/pacstall b/pacstall
--- a/pacstall
+++ b/pacstall
@@ -356,7 +356,7 @@ for i in "${@}"; do
     # Just add argument if doesn't start with a single hyphen.
     if ! [[ ${i} =~ ^-[^-] ]]; then
         # if argument is '-P' or '-K', add to beginning of argument list.
-        if [[ ${i} == "-P" ]] || [[ ${i} == "-K" ]] || [[ ${i} == "-N" ]]; then
+        if [[ ${i} == "-N" ]] || [[ ${i} == "-P" ]] || [[ ${i} == "-K" ]]; then
             argument_list=("${i}" "${argument_list[@]}")
         else
             argument_list+=("${i}")
@@ -368,7 +368,7 @@ for i in "${@}"; do
     # We remove the '-' prefix as we'll add it later.
     for j in $(echo "${i}" | sed 's|^-||' | sed 's|[[:upper:]]| &|g'); do
         # If current string is 'P', add to beginning of argument list.
-        if [[ ${j} == "P" ]] || [[ ${j} == "-disable-prompts" ]] || [[ ${j} == "K" ]] || [[ ${j} == "-keep" ]] || [[ ${j} == "N" ]] || [[ ${j} == "-no-install" ]]; then
+        if [[ ${j} == "N" ]] || [[ ${j} == "-no-install" ]] || [[ ${j} == "P" ]] || [[ ${j} == "-disable-prompts" ]] || [[ ${j} == "K" ]] || [[ ${j} == "-keep" ]]; then
             argument_list=("-${j}" "${argument_list[@]}")
         else
             argument_list+=("-${j}")
@@ -419,15 +419,13 @@ while [[ $1 != "--" ]]; do
             ;;
 
         -h | --help)
-            echo -e "Usage: pacstall [-h] [-V] {-I,-Il,-S,-R,-D,-A,-U,-L,-Up,-Qi,-T} [-P] [-K] [-N]
+            echo -e "Usage: pacstall [-h] [-V] {-I,-S,-R,-D,-A,-U,-L,-Up,-Qi,-T} [-P] [-K] [-N]
 
 An AUR inspired package manager for Ubuntu.
 
 Commands:
 	${BOLD}-I${NC}, ${BOLD}--install${NC} <package>
 		Install a package.
-	${BOLD}-Il${NC}, ${BOLD}--install-local${NC} <package>
-		Install a local pacscript.
 	${BOLD}-S${NC}, ${BOLD}--search${NC} <package>
 		Search for a package.
 	${BOLD}-R${NC}, ${BOLD}--remove${NC} <package>
@@ -492,7 +490,37 @@ Helpful links:
                     echo -e "~ Rick Pacsley ~"
                     exit 0
                 fi
-                export PACKAGE=$2
+				if [[ ${PACKAGE##*.} == "pacscript" ]]; then
+                	export type="install"
+                	export local="yes"
+                	PKGPATH="$(dirname "$2")"
+                	# Check if we need to cd into the directory first
+                	if [[ $PKGPATH == "." ]] && [[ ! -f "$PACKAGE".pacscript ]] && [[ -d $PACKAGE ]]; then
+                	    cd "$PACKAGE"
+                	elif [[ -d $PKGPATH ]]; then
+                	    cd "$PKGPATH"
+                	fi
+
+               		export PACKAGE="$(basename "$2" ".pacscript")" # Removes the suffix
+                	# Check if the file exist
+                	if [[ ! -f "$PACKAGE".pacscript ]]; then
+                		fancy_message error "$2 does not exist"
+                		shift
+                		continue
+                	fi
+                	if ! source "$STGDIR/scripts/install-local.sh"; then
+                	    fancy_message error "Failed to install ${GREEN}${PACKAGE}${NC}"
+                	    exit 1
+                	fi
+            		if [[ -s "LOGFILE" ]]; then
+            		    exit 1
+            		fi
+				else
+                	export type="install"
+                	export local="no"
+                	export PACKAGE=$2
+				fi
+
                 shift
                 if [[ -z $PACKAGE ]]; then
                     fancy_message error "You failed to specify a package"
@@ -505,9 +533,6 @@ Helpful links:
                     sudo touch "$STGDIR/repo/pacstallrepo.txt"
                     pacstall -A
                 fi
-
-                export type="install"
-                export local="no"
 
                 check_url "https://github.com" 2> /dev/null || check_url "https://gitlab.com" 2> /dev/null || {
                     fancy_message error "Could not connect to the internet"
@@ -536,52 +561,6 @@ Helpful links:
                     exit 1
                 fi
             done
-            exit 0
-            ;;
-
-        -Il | --install-local)
-
-            if [[ -z $2 ]]; then
-                fancy_message error "You failed to specify a package"
-                exit 1
-            fi
-
-            while [[ -n $2 ]]; do
-                export local="yes"
-
-                PKGPATH="$(dirname "$2")"
-                PACKAGE="$(basename "$2" ".pacscript")" # Removes the suffix
-                export PACKAGE
-
-                # Check if we need to cd into the directory first
-                if [[ $PKGPATH == "." ]] && [[ ! -f "$PACKAGE".pacscript ]] && [[ -d $PACKAGE ]]; then
-                    cd "$PACKAGE"
-                elif [[ -d $PKGPATH ]]; then
-                    cd "$PKGPATH"
-                fi
-
-                # Check if the file exist
-                if [[ ! -f "$PACKAGE".pacscript ]]; then
-                    fancy_message error "$2 does not exist"
-                    shift
-                    continue
-                fi
-                shift
-
-                check_url "https://github.com" 2> /dev/null || check_url "https://gitlab.com" 2> /dev/null || {
-                    fancy_message error "Could not connect to the internet"
-                    exit 1
-                }
-
-                if ! source "$STGDIR/scripts/install-local.sh"; then
-                    fancy_message error "Failed to install ${GREEN}${PACKAGE}${NC}"
-                    exit 1
-                fi
-                shift
-            done
-            if [[ -s "LOGFILE" ]]; then
-                exit 1
-            fi
             exit 0
             ;;
 
