-C can accept arguments
Former-commit-id: 7927207857def811d4bfc347f2a7566d4b0b7fb1 [formerly 6a1353afe8192dfc3ef5f2a6a01f5b01601e8add] [formerly 6b894fb8cb7ff7a1d35c564b0c744c0a45c3d9e3]
Former-commit-id: 3aeced5da53d510cf74af91cc66479780f767234
Former-commit-id: 234bfbedf996cf0bac159b349b570bdf2a032231

diff --git a/pacstall b/pacstall
--- a/pacstall
+++ b/pacstall
@@ -63,6 +63,10 @@ while test $# -gt 0; do
       fi
       PACPREFIX="apt install -y "
       PACKAGE=$2
+      if [[ -z "$PACKAGE" ]]; then
+        fancy_message error "You failed to specify a package"
+        exit 1
+      fi
       if [[ ! -e /usr/share/pacstall/repo/ ]]; then
           mkdir -p /usr/share/pacstall/repo
           touch /usr/share/pacstall/repo/pacstallrepo.txt
@@ -127,7 +131,12 @@ while test $# -gt 0; do
       fi
       ;;
     -C|--change-repo)
+      if [[ -z "$2" ]]; then
       . /usr/share/pacstall/scripts/change-repo.sh
+      else
+      echo "$2" | sudo tee /usr/share/pacstall/repo/pacstallrepo.txt >/dev/null 2>&1
+      exit
+      fi
       ;;
     -V|--version)
       COLOR='\e[1;36m'
@@ -161,6 +170,10 @@ while test $# -gt 0; do
       ;;
     -D|--download)
       PACKAGE=$2
+      if [[ -z "$PACKAGE" ]]; then
+        fancy_message error "You failed to specify a package"
+        exit 1
+      fi
       INSTALLING=0
       REPO=$(cat /usr/share/pacstall/repo/pacstallrepo.txt)
       source /usr/share/pacstall/scripts/download.sh
