Feat: Error out when running pacstall as root (#159)
* Fix(main): Error out when root

It's not recommended to run community scripts as root. So error out like AUR.

* Fix(main): exit 1 when root

* Fix(main): use fancy_message

* Fix(main): Lower the root check

Former-commit-id: 6da439886ee856988322fc8ec2e000dc92438bea

diff --git a/pacstall b/pacstall
--- a/pacstall
+++ b/pacstall
@@ -193,6 +193,13 @@ function download() {
 	fi
 }
 
+
+# Error out when run as root
+if [[ "$EUID" -eq 0 ]]; then
+	fancy_message error "Pacstall can't be run as root. Please run as a normal user."
+	exit 1
+fi
+
 # run sudo apt update if it's been more than a week
 [ -z "$(find -H /var/lib/apt/lists -maxdepth 0 -mtime -7)" ] && sudo apt-get update -qq
 
