fix: add guards to download and speed up url checking  (#535)
* fix: remove inaccurate package count and reword "auto updates"

* fix: better wording for git section

Co-authored-by: Sourajyoti Basak <wiz28@protonmail.com>

* fix: add guards to download and speed up url checking

* fix: remove doubled download and use check_url for connection testing only

* fix(install-local): add more error printing

Co-authored-by: Sourajyoti Basak <wiz28@protonmail.com>

diff --git a/pacstall b/pacstall
--- a/pacstall
+++ b/pacstall
@@ -194,7 +194,7 @@ function ask() {
 	done
 }
 function check_url() {
-    http_code="$(curl -o /dev/null -s -w "%{http_code}\n" -- "${1}")"
+    http_code="$(curl -o /dev/null -s --head --write-out '%{http_code}\n' -- "${1}")"
     case "${http_code}" in
         000)
             fancy_message error "Failed to download file, check your connection"
@@ -219,9 +219,9 @@ function check_url() {
 function download() {
 	sudo rm -f "${1##*/}"
 	if command -v axel > /dev/null; then
-		axel -ao "${1##*/}" "$1"
+		axel -ao "${1##*/}" "$1" || return 1
 	else
-		wget -q --show-progress --progress=bar:force -- "$1" 2>&1
+		wget -q --show-progress --progress=bar:force -- "$1" 2>&1 || return 1
 	fi
 }
 
@@ -354,7 +354,12 @@ while [[ ! "$1" == "--" ]]; do
 
 				export type="install"
 				export local="no"
-				
+
+				check_url "https://github.com" || check_url "https://github.com" || {
+					fancy_message error "Could not connect to the internet"
+					exit 1
+				}
+
 				if ! source "$STGDIR/scripts/search.sh"; then
 					fail_install=1
 					export fail_install
@@ -415,6 +420,11 @@ while [[ ! "$1" == "--" ]]; do
 				fi
 				shift
 
+				check_url "https://github.com" || check_url "https://github.com" || {
+					fancy_message error "Could not connect to the internet"
+					exit 1
+				}
+
 				if ! source "$STGDIR/scripts/install-local.sh"; then
 					fancy_message error "Failed to install ${GREEN}${PACKAGE}${NC}"
 					continue
@@ -434,6 +444,11 @@ while [[ ! "$1" == "--" ]]; do
 				fancy_message error "You failed to specify a package"
 				exit 1
 			fi
+
+			check_url "https://github.com" || check_url "https://github.com" || {
+				fancy_message error "Could not connect to the internet"
+				exit 1
+			}
 
 			source "$STGDIR/scripts/search.sh"
 			exit 0
@@ -512,6 +527,11 @@ while [[ ! "$1" == "--" ]]; do
 				fi
 			fi
 
+			check_url "https://github.com" || check_url "https://github.com" || {
+				fancy_message error "Could not connect to the internet"
+				exit 1
+			}
+
 			if curl --output /dev/null --silent --head --fail https://raw.githubusercontent.com/"$USERNAME"/pacstall/"$BRANCH"/pyproject.toml; then
 				fancy_message error "The repository you are trying to upgrade to contains a version of pacstall that cannot be updated from $(pacstall -V)"
 				fancy_message error "Visit https://github.com/$USERNAME/pacstall/tree/$BRANCH for more information on how to reinstall. Most packages will also need to be reinstalled"
@@ -542,6 +562,11 @@ while [[ ! "$1" == "--" ]]; do
 				shift
 				export type="download"
 
+				check_url "https://github.com" || check_url "https://github.com" || {
+					fancy_message error "Could not connect to the internet"
+					exit 1
+				}
+
 				if ! source "$STGDIR/scripts/search.sh"; then
 					((i++))
 					continue
@@ -565,6 +590,10 @@ while [[ ! "$1" == "--" ]]; do
 		;;
 
 		-Up|--upgrade)
+			check_url "https://github.com" || check_url "https://github.com" || {
+				fancy_message error "Could not connect to the internet"
+				exit 1
+			}
 			source "$STGDIR/scripts/upgrade.sh"
 
 			if [[ -s "LOGFILE" ]]; then
