Add files via upload
Former-commit-id: 2bb8914f4ac5a137cb5af5947d9e25a971a19cb8
Former-commit-id: cade0955d53721d39ac6dab01770ff42d209884f

diff --git a/pacstall b/pacstall
--- a/pacstall
+++ b/pacstall
@@ -196,43 +196,46 @@ while test $# -gt 0; do
       exit 0
       ;;
     -DL|--download-local)
-       cd /var/cache/pacstall/
-       package=$2
-       repo=$(cat /usr/share/pacstall/repo/pacstallrepo.txt)
-       if wget -q --show-progress:force:noscroll https://github.com/$repo/pacstall/raw/master/packages/$package/$package.tar.xz ; then
-       sudo tar -xf $package.tar.xz
-       cd $package
-       wget -O- https://raw.githubusercontent.com/$repo/pacstall/master/packages/$package/install.sh
-       cd ..
-       tar cfJ $package.tar.xz $package
-       if [[ $? -eq 0 ]] ; then
-       	exit 0
-       else
-       	exit 1
-       fi
-       wget -q --show-progress --progress=bar:force:noscroll https://github.com/$repo/pacstall/raw/master/packages/$package/$package.zip
-       unzip $package.zip
-       cd $package
-       wget -O- https://raw.githubusercontent.com/$repo/pacstall/master/packages/$package/install.sh
-       cd ..
-       tar cfJ $package.tar.xz $package
-       if [[ $? -eq 0 ]] ; then
-       exit 0
-       else
-       exit 1
-       fi
-       ;;
-     -IL|--install-local)
-       package=$2
-       tar xf $package.tar.xz
-       cd $package
-       sudo ./install.sh
-       if [[ $? -eq 0 ]] ; then
-       exit 0
-       else
-       echo "Failed to install $package"
-       exit 1
-       fi
+      cd /var/cache/pacstall/
+      package=$2
+      repo=$(cat /usr/share/pacstall/repo/pacstallrepo.txt)
+      if wget -q --show-progress:force:noscroll https://github.com/$repo/pacstall/raw/master/packages/$package/$package.tar.xz ; then
+      sudo tar -xf $package.tar.xz
+      cd $package
+      wget -O- https://raw.githubusercontent.com/$repo/pacstall/master/packages/$package/install.sh
+      cd ..
+      tar cfJ $package.tar.xz $package
+      if [[ $? -eq 0 ]] ; then
+      exit 0
+      else
+      exit 1
+      fi
+      else 
+      wget -q --show-progress --progress=bar:force:noscroll https://github.com/$repo/pacstall/raw/master/packages/$package/$package.zip
+      unzip $package.zip
+      cd $package
+      wget -O- https://raw.githubusercontent.com/$repo/pacstall/master/packages/$package/install.sh
+      cd ..
+      tar cfJ $package.tar.xz $package
+      if [[ $? -eq 0 ]] ; then
+      exit 0
+      else
+      exit 1
+      fi
+      fi
+      ;;
+    -IL|--install-local)
+      package=$2
+      tar xf $package.tar.xz
+      cd $package
+      sudo ./install.sh
+      if [[ $? -eq 0 ]] ; then
+      exit 0
+      else
+      echo "Failed to install $package"
+      exit 1
+      fi
+      ;;
      -Dep)
        
       ;;
