Release Amaranth (#40)
* General fixes

* Fixed things

* Fix `SC1001` on line 259

* Fix `SC2181` on line 202

* Fix `SC2181` on line 147

* Fix `SC2181` on line 116

* Fix `SC2181` on line 113

* Fix `SC2181` on line 84

* Fix `SC2006` on line 62

* Fix `SC2002` on line 59

* Fix `SC2002` on line 37

* Fix `SC1001` on line 222

* Fix `SC2010` on line 59

* Fix `SC2035` on line 59

* Fix `SC2035` on lines

* Fixed things

* Revert "Feature/bugfix"

* Added codefactor badge

* Added git fsck --full to check integrity of git repo

* Fixed version checker

* Fix upgrade issue

* Branch update with -U (#15)

* Add develop flag with -Ud

* Pacstall can update to different branches with pacstall -U branch

* Pacstall can update from different users

* Add quotes

Co-authored-by: Sourajyoti Basak <wiz28@protonmail.com>

* Change `nano` to `editor`

* Add USERNAME instead of USER and fix quotes (#24)

* Remove outdated info (#25)

* Fix bugs in the update code block (#26)

* Change `-z` to `-n` (#28)

* Create labeler.yml

* [enhancement] Configure the Auto-Labeler, test drive 2 (#31)

* [Feature] Add pacdeps to -Qi (#32)

* Add pacdeps to -Qi

* Update misc/scripts/install-local.sh

Co-authored-by: Sourajyoti Basak <wiz28@protonmail.com>

* Update pacstall

Co-authored-by: Sourajyoti Basak <wiz28@protonmail.com>

* Fix suggestion

* Fix suggestion

Co-authored-by: Sourajyoti Basak <wiz28@protonmail.com>

* Add filters to the labeler (#36)

* Add filters to the labeler

* Fix issues

* Fix -Qi not showing depends (#38)

* Fix #37

* Fixing stuff

* Update pacstall

Co-authored-by: Sourajyoti Basak <wiz28@protonmail.com>

* Update pacstall

Co-authored-by: Sourajyoti Basak <wiz28@protonmail.com>

Co-authored-by: Sourajyoti Basak <wiz28@protonmail.com>

* Fix spacing

* Release/amaranth (#39)

* Bump version

* Fix spacing issue

* Update manpage

* Update -Qi

* Quick bugfix

* ->

* Replace `editor` with `sensible-editor`

* Fix typo with -R flag

* Fix reduntant line

* Add guard to -Qi

* Add more info to readme commands

* Fix typos, prettify, change `git flow` link

* Fix spacing

Co-authored-by: Sourajyoti Basak <wiz28@protonmail.com>

Co-authored-by: Sourajyoti Basak <wiz28@protonmail.com>
Former-commit-id: fe3f55cb3dbd22fa9762a760f1f227cea18bd5d5
Former-commit-id: 457d98d2c1fae91a1e37a7567ce310e975b9e764

diff --git a/pacstall b/pacstall
--- a/pacstall
+++ b/pacstall
@@ -172,6 +172,7 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
       -I --install, Installs package
       -S --search, Search for package
       -R --remove, Removes package
+      -D --download, Downloads script
       -C --change-repo, Chooses repo
       -U --update, Update script
       -V --version, Prints pacstall version
@@ -218,7 +219,7 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
       REPO=$(cat /usr/share/pacstall/repo/pacstallrepo.txt) 
       INPUT=$2
       # If string is absolute dir
-      if [[ "$string" == *\/* ]] || [[ "$string" == *\\* ]] ; then
+      if [[ "$string" == */* ]] || [[ "$string" == *\\* ]] ; then
         cd $(pwd)
         parentdir="$(dirname "$INPUT")"
         eval dir="$parentdir"
@@ -239,7 +240,7 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
       PACKAGE=$2
       # Check if $2 is filled (not empty) because if not, stow will remove every package (from experience, oof)
       if [[ -z "$PACKAGE" ]]; then
-        fancy_message error "You did not specify a package to remove"
+        fancy_message error "You failed to specify a package"
         exit 1
       fi
       source /var/log/pacstall_installed/"$PACKAGE"
@@ -258,9 +259,10 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
             source <(cat /var/cache/pacstall/"$PACKAGE"/$(pacstall -Qi "$PACKAGE" | sed 's/: /=/g' | sed -n -e 's/version=//p')/"$PACKAGE".pacscript)
 	        removescript
         fi
-        if [ -z "$dependencies" ]; then
+        if [ -n "$dependencies" ]; then
             fancy_message info "You may want to remove ${BLUE}$dependencies${NC}"
         fi
+        sudo rm -f /var/log/pacstall_installed/"$PACKAGE"
         exit
       else
         fancy_message error "$PACKAGE does not exist or not properly symlinked"
@@ -277,11 +279,10 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
       ;;
     -V|--version)
       if [[ -z "$2" ]]; then
-        echo -e "1.2 ${BIBlue}Capri${NC}"
+        echo -e "1.3 ${BIPurple}Amaranth${NC}"
         exit 0
       else
-        if [[ $(pacstall -L | grep "$2" | cut -d' ' -f2-) ]]; then
-          echo -e "${BOLD}${GREEN}pacstall -L | grep ""$2"" | cut -d' ' -f2-${NORMAL}${NC}"
+        if pacstall -Qi "$2" | grep 'version' | cut -d ":" -f2 | sed 's/ //g'; then
           exit
         else
           fancy_message error "$2 doesn't exist"
@@ -290,15 +291,23 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
       fi
       ;;
     -U|--update)
+      USERNAME="$2"
+      BRANCH="$3"
+      if [[ -z "$BRANCH" ]]; then
+          BRANCH="master"
+      fi
+      if [[ -z "$USERNAME" ]]; then
+          USERNAME="pacstall"
+      fi
       if ask "Are you sure you want to update pacstall?" Y; then
         for i in {change-repo.sh,search.sh,download.sh,install-local.sh,upgrade.sh}; do
-            sudo wget -q -N https://raw.githubusercontent.com/pacstall/pacstall/master/misc/scripts/"$i" -P /usr/share/pacstall/scripts 2>/dev/null 
+            sudo wget -q -N https://raw.githubusercontent.com/"$USERNAME"/pacstall/"$BRANCH"/misc/scripts/"$i" -P /usr/share/pacstall/scripts 2>/dev/null 
         done
-        sudo wget -q -N https://raw.githubusercontent.com/pacstall/pacstall/master/pacstall -P /bin 2>/dev/null
+        sudo wget -q -N https://raw.githubusercontent.com/"$USERNAME"/pacstall/"$BRANCH"/pacstall -P /bin 2>/dev/null
         sudo mkdir -p /usr/share/bash-completion/completions
-        sudo wget -q -O /usr/share/bash-completion/completions/pacstall https://raw.githubusercontent.com/pacstall/pacstall/master/misc/completion/bash 2>/dev/null
+        sudo wget -q -O /usr/share/bash-completion/completions/pacstall https://raw.githubusercontent.com/"$USERNAME"/pacstall/"$BRANCH"/misc/completion/bash 2>/dev/null
         if command -v fish &>/dev/null; then
-            sudo wget -q -O /usr/share/fish/vendor_completions.d/pacstall.fish https://raw.githubusercontent.com/pacstall/pacstall/master/misc/completion/fish 2>/dev/null
+            sudo wget -q -O /usr/share/fish/vendor_completions.d/pacstall.fish https://raw.githubusercontent.com/"$USERNAME"/pacstall/"$BRANCH"/misc/completion/fish 2>/dev/null
         fi
         echo '
     ____                  __        ____
@@ -307,8 +316,8 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
  / ____/ /_/ / /__(__  ) /_/ /_/ / / /
 /_/    \__,_/\___/____/\__/\__,_/_/_/
 '
-        fancy_message info "You are at version $(pacstall -V)"
-    	fancy_message warn "Be sure to check our GitHub release page to make sure you have no incompatible code: https://github.com/pacstall/pacstall"
+      fancy_message info "You are at version $(pacstall -V)"
+      fancy_message warn "Be sure to check our GitHub release page to make sure you have no incompatible code: https://github.com/$USERNAME/pacstall/tree/$BRANCH"
         exit 0
       else
         exit 1
@@ -362,13 +371,28 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
           fancy_message error "You failed to specify a package"
           exit 1
       fi
+      if [ ! -f /var/log/pacstall_installed/"$PACKAGE" ]; then
+          fancy_message error "Package does not exist"
+          exit 1
+      fi
       source /var/log/pacstall_installed/"$PACKAGE"
       echo "name: $PACKAGE"
       echo "version: $version"
       echo "size: $(du -sh /usr/src/pacstall/"$PACKAGE" | awk '{print $1}')"
       echo "description: ""$description"""
       echo "date installed: ""$date"""
-      echo "maintainer: ""$maintainer"""
+      if [[ -n $maintainer ]]; then
+        echo "maintainer: ""$maintainer"""
+      fi
+      if [[ -n $pacdepslist ]]; then
+          echo "pacstall dependencies: ""${pacdepslist[*]}"""
+      fi
+      if [[ -n $dependencies ]]; then
+          echo "dependencies: ""$dependencies"""
+      fi
+      if [[ -n $build_dependencies ]]; then
+          echo "build dependencies: ""$build_dependencies"""
+      fi
       exit
       ;;
      *)
