feat(search.sh): keyword and info search (#1201)
Co-authored-by: ook37 <oren+12345@taumoda.com>

diff --git a/pacstall b/pacstall
--- a/pacstall
+++ b/pacstall
@@ -653,9 +653,9 @@ done
 declare -A arg_map=(
     ["--install"]="-I" ["--search"]="-S" ["--remove"]="-R" ["--download"]="-D"
     ["--add-repo"]="-A" ["--remove-repo"]="-Rr" ["--update"]="-U" ["--list"]="-L" ["--upgrade"]="-Up"
-    ["--query-info"]="-Qi" ["--tree"]="-T" ["--version"]="-V" ["--help"]="-h"
-    ["--build"]="-B" ["--keep"]="-K" ["--disable-prompts"]="-P" ["--nocheck"]="-Nc"
-    ["--quality-assurance"]="-Qa" ["--quiet"]="-Q" ["--nosandbox"]="-Ns"
+    ["--search-description"]="-Sd" ["--search-info"]="-Si" ["--cache-info"]="-Ci"
+    ["--quality-assurance"]="-Qa" ["--tree"]="-T" ["--version"]="-V" ["--help"]="-h" ["--build"]="-B"
+    ["--keep"]="-K" ["--disable-prompts"]="-P" ["--nocheck"]="-Nc" ["--quiet"]="-Q" ["--nosandbox"]="-Ns"
 )
 declare -A hashed_arguments
 unique_argument_list=()
@@ -668,8 +668,8 @@ for arg in "${argument_list[@]}"; do
 done
 
 # Check if only one command flag is being used
-short_commands=("-I" "-S" "-R" "-D" "-A" "-Rr" "-U" "-L" "-Up" "-Qi" "-Qa" "-T" "-V" "-h")
-long_commands=("--install" "--search" "--remove" "--download" "--add-repo" "--remove-repo" "--update" "--list" "--upgrade" "--query-info" "--quality-assurance" "--tree" "--version" "--help")
+short_commands=("-I" "-S" "-R" "-D" "-A" "-Rr" "-U" "-L" "-Up" "-Qa" "-Sd" "-Si" "-Ci" "-T" "-V" "-h")
+long_commands=("--install" "--search" "--remove" "--download" "--add-repo" "--remove-repo" "--update" "--list" "--upgrade" "--quality-assurance" "--search-description" "--search-info" "--cache-info" "--tree" "--version" "--help")
 commands=("${short_commands[@]}" "${long_commands[@]}")
 matches=($(comm -12 <(sort <(printf "%s\n" "${unique_argument_list[@]}")) <(sort <(printf "%s\n" "${commands[@]}"))))
 if ((${#matches[@]} <= 1)); then
@@ -686,8 +686,8 @@ function lock() {
     { ignore_stack=false; set -o pipefail; trap stacktrace ERR RETURN; }
     # Total number of options flags, increase when needed
     local option_flags=5
-    local ignore_short="-S -D -A -Rr -V -L -Qi -T -h"
-    local ignore_long="--search --download --add-repo --remove-repo --version --query-info --tree --help"
+    local ignore_short="-S -D -A -Rr -V -L -T -Sd -Si -Ci -h"
+    local ignore_long="--search --download --add-repo --remove-repo --version --tree --search-description --search-info --cache-info --help"
     local ignore="$ignore_short $ignore_long"
 
     for ((i = 1; i <= option_flags + 1; i++)); do
@@ -741,7 +741,7 @@ while [[ $1 != "--" ]]; do
             ;;
 
         -h | --help)
-            echo -e "Usage: pacstall [-h] {-I,-S,-R,-D,-A,-Rr,-U,-L,-Up,-Qa,-Qi,-T,-V} [-P] [-K] [-B] [-Nc] [-Q] [-Ns]
+            echo -e "Usage: pacstall [-h] {-I,-S,-R,-D,-A,-Rr,-U,-L,-Up,-Qa,-Sd,-Si,-Ci,-T,-V} [-P] [-K] [-B] [-Nc] [-Q] [-Ns]
 
 An AUR inspired package manager for Ubuntu.
 
@@ -766,10 +766,14 @@ Commands:
         Upgrade all installed packages.
     ${BOLD}-Qa${NC}, ${BOLD}--quality-assurance${NC} <package>#<number>
         Test a package PR from downstream. Optional: @[provider]:[owner]/[repo]
-    ${BOLD}-Qi${NC}, ${BOLD}--query-info${NC} <package>
-        Query information about a package.
+    ${BOLD}-Sd${NC}, ${BOLD}--search-description${NC} <package>
+        Search for a package or description keyword.
+    ${BOLD}-Si${NC}, ${BOLD}--search-info${NC} <package>
+        Query information about a remote package.
+    ${BOLD}-Ci${NC}, ${BOLD}--cache-info${NC} <package>
+        Query information about an installed package.
     ${BOLD}-T${NC}, ${BOLD}--tree${NC} <package>
-        Display a tree graph of a package.
+        Display a tree graph of an installed package.
     ${BOLD}-V${NC}, ${BOLD}--version${NC}
         Display the version number.
     ${BOLD}-h${NC}, ${BOLD}--help${NC}
@@ -930,7 +934,10 @@ Helpful links:
             exit 0
             ;;
 
-        -S | --search)
+        -S | --search | -Sd | --search-description)
+            if [[ ${1} == "-Sd" || ${1} == --search-description ]]; then
+                DESCON=true
+            fi
 
             export SEARCH=$2
             if [[ -z $SEARCH ]]; then
@@ -944,6 +951,47 @@ Helpful links:
                 exit 1
             }
 
+            # shellcheck source=./misc/scripts/search.sh
+            source "$SCRIPTDIR/scripts/search.sh"
+            exit 0
+            ;;
+
+        -Si | --search-info)
+            unset CHILD
+            INFOQUERY="${2}"
+            if [[ $2 =~ ^([a-zA-Z0-9_.-]+)(:([a-zA-Z0-9_.-]+))(@(.+))$ ]]; then
+                PACKAGE="${BASH_REMATCH[1]}:pkgbase"
+                if [[ ${BASH_REMATCH[2]} == ":"* ]]; then
+                    CHILD="${BASH_REMATCH[2]/\:/}"
+                else
+                    CHILD="${BASH_REMATCH[3]}"
+                fi
+                if [[ ${BASH_REMATCH[3]} =~ '@' ]]; then
+                    PACKAGE+="${BASH_REMATCH[3]}"
+                elif [[ -n ${BASH_REMATCH[5]} ]]; then
+                    PACKAGE+="@${BASH_REMATCH[5]}"
+                fi
+            elif [[ $2 =~ ^([a-zA-Z0-9_.-]+)(@(.+))$ ]]; then
+                PACKAGE="${2}"
+            elif [[ ${2} =~ ':' ]]; then
+                PACKAGE="${2%:*}:pkgbase"
+                CHILD="${2#*:}"
+            else
+                PACKAGE="${2}"
+            fi
+            [[ ${CHILD} == "pkgbase" ]] && unset CHILD
+            export PACKAGE CHILD
+            if [[ -z $PACKAGE ]]; then
+                fancy_message error "You failed to specify a package"
+                exit 1
+            fi
+            check_url "https://github.com" 2> /dev/null || check_url "https://gitlab.com" 2> /dev/null || {
+                fancy_message error "Could not connect to the internet"
+                suggested_solution "Confirm that the URLs '${UGreen}https://github.com${NC}' or '${UGreen}https://gitlab.com${NC}' are accessible"
+                exit 1
+            }
+
+            SEARCHINFO=true
             # shellcheck source=./misc/scripts/search.sh
             source "$SCRIPTDIR/scripts/search.sh"
             exit 0
@@ -1188,7 +1236,7 @@ Helpful links:
             exit 0
             ;;
 
-        -Qi | --query-info)
+        -Ci | --cache-info)
             PACKAGE=$2
             QUERY=$3
             # shellcheck source=./misc/scripts/query-info.sh
